{{ if eq .chezmoi.os "linux" }}
[".local/bin/nvim"]
    type = "file"
    url = "https://github.com/neovim/neovim/releases/download/stable/nvim.appimage"
    refreshPeriod = "672h"
    executable = true
{{ end }}