font:
  normal:
    family: "FiraCode Nerd Font"
    style: Light
  bold:
    family: "FiraCode Nerd Font"
    style: Medium
  bold_italic:
    family: "FiraCode Nerd Font"
    style: "Medium Italic"
  italic:
    family: "FiraCode Nerd Font"
    style: "Light Italic"
  size: 14
  use_thin_strokes: true
