# vim: ft=tmux

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=default,fg=#666666"

set -g pane-border-status top

set -g pane-border-indicators   off
set -g pane-border-style        "fg=#222222"
set -g pane-active-border-style "fg=#444444"
set -g pane-border-format       "#[fg=#444444] #{pane_title} "

set -g status-right ""

set -g status 2
set -g status-format[0] ""
set -g status-format[1] "#[fg=#666666,bold]#S #[fg=#1e1e1e] │ #{W:#[fg=#353535] #I #W ,#[fg=#bbbbbb,bg=default] #I #W }"
