# vim: ft=tmux

source-file ~/.config/tmux/options.conf
source-file ~/.config/tmux/keybindings.conf
source-file ~/.config/tmux/statusline.conf

# macOS-specific overrides
if-shell "uname | grep -q Darwin" \
  "source-file ~/.config/tmux/macos.conf"

source-file ~/.config/tmux/claude.conf

# ── Plugins ───────────────────────────────
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-strategy-vim 'session'
set -g @continuum-restore 'on'

if-shell '[ -f ~/.tmux/plugins/tpm/tpm ]' \
  "run '~/.tmux/plugins/tpm/tpm'"
