# vim:fileencoding=utf-8:foldmethod=marker
include monokai_pro_spectrum.conf 

font_family MonoLisa
font_features MonoLisa-Medium +zero +ss04 +ss07 +ss08 +ss09
font_features MonoLisa-MediumItalic +zero +ss04 +ss07 +ss08 +ss09
symbol_map U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E634,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF Symbols Nerd Font Mono
font_size 14
adjust_line_height 21
disable_ligatures never

window_padding_width 7
draw_minimal_borders yes

cursor_shape block
cursor_blink_interval 0

enable_audio_bell no

macos_titlebar_color background
macos_quit_when_last_window_closed yes
macos_option_as_alt yes
