# Author: Gheorghita Hurmuz <hurmuz.gheorghita@pm.me>

# ======================================
# Keybinding
# ======================================
# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Spliting
bind | split-window -h
bind - split-window -v

# Selecting
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# ======================================
# Utils
# ======================================
set -g base-index 1
setw -g pane-base-index 1
set -s escape-time 1
set -g mouse on
set -g renumber-windows on

# ======================================
# Appereance
# ======================================
# set -g default-terminal "xterm-256color"
# if 'infocmp -x alacritty > /dev/null 2>&1' 'set -g default-terminal "alacritty"'
# set -ag terminal-overrides ",alacritty:RGB"
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# StatusBar
set -g status-justify left
set -g status-style "bg=default,fg=white"
set -g status-right "#[fg=green]  #[fg=white]+ #[fg=magenta]  #[fg=white]= #[fg=red] "
set -g status-left-length 20
set -g status-left "#[fg=green] #S: #[fg=white]"

set -g window-status-format "[#I]#[fg=white]#W"
set -g window-status-current-format "#[bg=green]#[fg=black][#I]#W"

# Border line
set -g pane-border-style "bg=default,fg=white"
set -g pane-active-border-style "bg=default,fg=white"
