#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_border on
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 4

yabai -m config active_window_border_topmost on
yabai -m config window_shadow off
yabai -m config window_opacity off
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xFFFC618D

yabai -m space 1 --label core
yabai -m space 2 --label work_browser
yabai -m space 3 --label code

yabai -m rule --add app="^Brave Browser$" space=core
yabai -m rule --add app="^Mail$" space=core
yabai -m rule --add app="^Obsidian$" space=core
yabai -m rule --add app="^Zotero$" space=core
yabai -m rule --add app="^Google Chrome$" space=work_browser
yabai -m rule --add app="^Code$" space=code


yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_launched action="yabai -m query --windows --window $YABAI_WINDOW_ID | jq -er '.\"can-resize\"' || yabai -m window $YABAI_WINDOW_ID --toggle float && yabai -m window $YABAI_WINDOW_ID --grid 4:4:1:1:2:2"
