setopt HIST_IGNORE_ALL_DUPS
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY

export HISTTIMEFORMAT="[%F %T] "
export HISTFILE="$HOME/.zsh_history"
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000

