# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
rev = "1c75faff4d8584afe090b06db11991c8c8d62055"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.0"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
tag = "0.7.1"
apply = ["defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
tag = "0.35.0"
apply = ["defer"]

[plugins.starship]
inline = 'command -v starship &> /dev/null && eval "$(starship init zsh)"'

[plugins.zoxide]
inline = 'command -v zoxide &> /dev/null && eval "$(zoxide init zsh)"'

[plugins.fnm]
inline = 'command -v fnm &> /dev/null && eval "$(fnm env --use-on-cd)"'
